    <div class="content p-4">  
        <div class="row">
            <div class="col-md-12">
                <h2 class="mb-4">Total de Músicas</h2>
            </div>
            <?php foreach($this->view->totalPorGenero as $total):?>
            <div class="col-md-3">
                <div class="card bg-light shadow rounded mb-3">
                    <div class="card-header bg-dark text-white">Músicas <?=$total['genero']?></div>
                    <div class="card-body">
                        <h5 class="card-title">
                        <?=$total['total']?> músicas
                        </h5>
                    </div>
                </div>    
            </div>
            <?php endforeach ?>
        </div>
    </div>
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="js/bootadmin.min.js"></script>
   