<div class="content p-4">  
        <div class="row">
        <div class="col-md-6">
        <h2 class="mb-4">Editar música</h2>
            <div class="card mb-4  shadow rounded">
                <div class="card-body">
                    <form action="/atualiza" method="post">
                        <div class="form-group">
                            <label for="exampleInputEmail1">
                                <strong>Nome da música:</strong>
                            </label>
                            <input type="text" name="nome_musica" class="form-control border border-dark" id="#nome_musica" value="<?= $this->view->dados['musica'] ?>">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">
                            <strong>Nome do autor ou banda:</strong>
                            </label>
                            <input type="text" name="nome_autor" class="form-control border border-dark" id="nome_autor" value="<?= $this->view->dados['autor'] ?>">
                        </div>
                        <input type="hidden" name="id" value="<?= $this->view->dados['id'] ?>">
                        <div class="pt-3">
                            <button type="submit" class="btn btn-dark">Atualizar</button>
                        </div>
                    </form>
                </div>
            </div>    
            <script src="js/jquery.min.js"></script>
            <script src="js/bootstrap.bundle.min.js"></script>
            <script src="js/bootadmin.min.js"></script>
    