    <div class="content p-4 ">  
        <div class="alert">     
        </div>
        <div class="row ">
            <div class="col-md-8">
                <h2 class="mb-4">Upload de Músicas</h2>
                <div class="card mb-4 shadow rounded">
                    <div class="card-body">
                        <form action="/processaupload"  method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label  for="exampleInputEmail1">
                                    <strong>Nome da música:</strong>
                                </label>
                                <input type="text" name="nome_musica" class="form-control border border-dark" id="#nome_musica" placeholder="Ex: Blinding Lights">
                            </div>
                            <div class="form-group">
                                <label  class="" for="exampleInputEmail1">
                                <strong>Nome do autor ou banda:</strong>
                                </label>
                                <input type="text" name="nome_autor" class="form-control border border-dark" id="nome_autor"  placeholder="Ex: The Weeknd">
                            </div>
                            <div class="form-group">
                                <label class="" for="exampleFormControlSelect1">
                                    <strong> Selecione o genêro:</strong>
                                </label>
                                <select class="form-control border border-dark" name="genero" id="genero">
                                    <option value='1'>Eletrônica</option>
                                    <option value='2'>Rap</option>
                                    <option value='3'>Evangélica</option>
                                    <option value='4'>Para Estudar</option>
                                    <option value='5'>Reggae</option>
                                    <option value='6'>Para Programar</option>
                                    <option value='7'>Anime</option>
                                    <option value='8'>Forró</option>
                                </select>
                            </div>
                            <div class="form-group">
   						        <label  class="" for="exampleFormControlFile1">
                                   <strong>Selecione o arquivo:</strong>
                                </label>
    					        <input type="file" name="arquivo" class="form-control-file" id="arquivo" b>
  				             </div>
                            <div class="progress mb-4">
  						        <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 0%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" ></div>
					        </div>
                            <div class="card-footer bg-white">
                                <button type="submit" class="btn btn-dark">Enviar</button>
                                <a href="/" class="btn btn-success ml-2">Ver na playlist</a>
                            </div>
                        </form>
                    </div>
                </div>    
            </div>
        </div>
    </div> 
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="js/bootadmin.min.js"></script>
    <script src="js/upload.js"></script>
    