<section id="home" class="d-flex capa"><!--Inicio Home-->
      <div class="container align-self-center">
        <div class="row">
          <div class="col-md-12">
            <div id="carousel-home" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner"><!--Inicio Inner-->
                <div class="carousel-item active">
                 <h1>Sistema de Playlist</h1>
                 <a href="#playlist" class="btn btn-lg btn-custom btn-verde bg-success ">
                    Acessar playlist
                 </a>
                </div>
                <div class="carousel-item">
                   <h1>As melhores músicas</h1>
                   <a href="#playlist" class="btn btn-lg btn-custom btn-verde bg-success">
                    Acessar playlist
                   </a>
                </div>
              </div><!--Fim Inner-->
              <!--Inicio controles-->
              <a class="carousel-control-prev" href="#carousel-home" role="button" data-slide="prev">
                 <i class="fas fa-angle-left fa-3x"></i>
              </a>  
              <a class="carousel-control-next" href="#carousel-home" role="button" data-slide="next">
                <i class="fas fa-angle-right fa-3x"></i>
              </a><!--Fim controles-->
            </div>
          </div>
        </div>
      </div>
    </section><!--Fim Home-->  
    <section id="playlist"><!--Inicio section Playlist-->  
      <div class="container caixa">
        <div class="row">
          <div class="col-md-12" >
            <h2>Escolha sua playlist</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 pt-5">
            <div class="card shadow rounded">
              <div class="card-body" >
                <h5 class="card-title" >Eletrônica</h5>
                <p class="card-text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod, quaerat sint? Nihil repellendus culpa consec.</p>
                <a href="/eletronica" class="btn btn-success btn-verde btn-visitar btn-visitar">Visitar</a>
              </div>
            </div>
          </div>
          <div class="col-md-3 pt-5">
           <div class="card shadow rounded">
              <div class="card-body">
                <h5 class="card-title">Rap</h5>
                <p class="card-text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod, quaerat sint? Nihil repellendus culpa consec.</p>
                <a href="/rap" class="btn btn-success btn-verde btn-visitar">Visitar</a>
              </div>
            </div>
          </div>
          <div class="col-md-3 pt-5">
            <div class="card shadow rounded">
              <div class="card-body">
                <h5 class="card-title">Evangélica</h5>
                <p class="card-text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod, quaerat sint? Nihil repellendus culpa consec.</p>
                <a href="/evangelica" class="btn btn-success btn-verde btn-visitar">Visitar</a>
              </div>
            </div>
          </div>
          <div class="col-md-3 pt-5">
            <div class="card shadow rounded">
              <div class="card-body">
                <h5 class="card-title">Para Estudar</h5>
                <p class="card-text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod, quaerat sint? Nihil repellendus culpa consec.</p>
                <a href="/para-estudar" class="btn btn-success btn-verde btn-visitar">Visitar</a>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 pt-5">
            <div class="card shadow rounded">
              <div class="card-body">
                <h5 class="card-title">Reggae</h5>
                <p class="card-text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod, quaerat sint? Nihil repellendus culpa consec.</p>
                <a href="/reggae" class="btn btn-success btn-verde btn-visitar">Visitar</a>
              </div>
            </div>
          </div>
          <div class="col-md-3 pt-5">
           <div class="card shadow rounded">
              <div class="card-body">
                <h5 class="card-title">Para Programar</h5>
                <p class="card-text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod, quaerat sint? Nihil repellendus culpa consec.</p>
                <a href="/para-programar" class="btn btn-success btn-verde btn-visitar">Visitar</a>
              </div>
            </div>
          </div>
          <div class="col-md-3 pt-5">
            <div class="card shadow rounded">
              <div class="card-body">
                <h5 class="card-title">Anime</h5>
                <p class="card-text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod, quaerat sint? Nihil repellendus culpa consec.</p>
                <a href="/anime" class="btn btn-success btn-verde btn-visitar">Visitar</a>
              </div>
            </div>
          </div>
          <div class="col-md-3 pt-5">
            <div class="card shadow rounded">
              <div class="card-body">
                <h5 class="card-title">Forró</h5>
                <p class="card-text">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod, quaerat sint? Nihil repellendus culpa consec.</p>
                <a href="/forro" class="btn btn-success btn-verde btn-visitar">Visitar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <section class="pb-4"></section>
      </section><!--Fim section Playlist-->       
      