   
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                    </div>
                    <div class="titulo-footer col-md-6 d-flex justify-content-center mt-3">
                        <p>Todos direitos reservados &copy;</p>	
                    </div>
                    <div class="col-md-3" >
                    <a href="" class="btn btn-outline-light btn-footer">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a href="" class="btn btn-outline-light ml-2 btn-footer">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="" class="btn btn-outline-light ml-2 btn-footer">
                        <i class="fab fa-instagram"></i>
                    </a>
                    </div>
                </div>
            </div>
        </footer>
        <script src="js/jquery.min.js"></script>
        <script src="js/bootstrap.bundle.min.js"></script>
        <script src="js/scroll.js"></script>
    </body>
</html>    