    <header><!--Inicio cabeçalho-->
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top navbar-custon">
        <div class="container">
          <a class="navbar-brand" href="">
            <span id="logo" class="ml-3">
            <img id="img-logo" src="imagens/logo.svg" > PlaySound 
            </span>
          </a>
          <button class="navbar-toggler mr-2" type="button" data-toggle="collapse" data-target="#navbar"> 
            <span class="navbar-toggler-icon"></span>
          </button>
           <div class="collapse navbar-collapse" id="navbar">
             <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="">Podcast</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="">Músicas</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="">Playlist</a>
                </li>
                <li class="nav-item divisor d-none d-md-block">
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="">Sobre</a>
                </li>
             </ul>
           </div>
        </div>
      </nav>
    </header><!--Inicio cabeçalho-->