
    <section><!--Inicio palylist-->
      <div class="container">
        <div class="row playlist">
          <div class="col-md-12 caixa">
            <h2 class="mb-4 mt-4">
              Playlist <?= $this->view->titulo?>
            </h2>

            <div class="form-group col-md-4">
                <form method="get" action="/playlist">
                    <div class="input-group mb-4">
                        <input type="hidden" name="genero" value="<?= $this->view->genero?>">
                        <input type="hidden" name="id" value="<?= $this->view->idGenero?>">
                        <input type="text" class="form-control" placeholder="Pesquisar música" name="pesquisa">                                
                        <button class="btn btn-dark ml-2" type="submit"><i class="fas fa-search"></i></button>
                    </div>
                </form>
            </div>

            <?php if(isset( $this->view->descricao)) {?>
              <p>
                <strong>Descrição:</strong>
                <?= $this->view->descricao ?>
              </p>
            <?php } ?>
            <?php if(isset($this->view->total)) {?>
              <p>
                <strong>Total de músicas: </strong>
                <?= $this->view->total ?> músicas
              </p>
            <?php } ?>

            <?php if($this->view->musicas == null && $this->view->pesquisa == true): ?>
                    <div class="text-danger col-md-12 mb-4">
                        Não foi encontrado nenhuma música com: <strong><?=$this->view->pesquisaMusica?></strong> 
                        <a href="/playlist?genero=<?=$this->view->genero?>&id=<?=$this->view->idGenero?>" class="ml-4 "> <div><i class="fas fa-arrow-left"></i> Voltar</div> </a>
                    </div>
            <?php endif ?>
            <?php if($this->view->musicas && $this->view->pesquisa == true): ?>
                    <div class="text-success col-md-10 mb-4">
                        Resultados da pesquisa para: <strong class="text-success"> <?=$this->view->pesquisaMusica?> </strong> 
                        <a href="/playlist?genero=<?=$this->view->genero?>&id=<?=$this->view->idGenero?>" class="ml-4 "> <div><i class="fas fa-arrow-left"></i> Voltar</div> </a> 
                    </div>
            <?php endif ?>
          </div>
            
          <div class="col-md-8 " id="lista">
            <ul class="list-group list-group-flush" id="playlist">
                <?php foreach ($this->view->musicas as $musica) { ?>
                 
              <li class="list-group-item">
                <a href="<?= $this->view->diretorio ?><?=$musica['arquivo']?>" class="nome-musica">
                  <i class="fa fa-play mr-1"></i>
                  <?= $musica['musica']?> - <?= $musica['autor']?>

                </a>
              </li> 
                <?php } ?>

          </div>
        </div>
      </div>
    </section><!--Fim section playlist-->
    <div class="container-fluid fixed-bottom container-barra-play">
      <div class="d-flex justify-content-center d-flex align-items-center" >
        <div class="row barra-play">
          <div class="col d-none d-md-block">
            <div class="mr-2 btn-barra-play">
              <a href="#" class="btn btn-dark" onclick="playlist.prevTrack();">
                <i class="fa fa-fast-backward"></i>
              </a>
            </div>
            <div class="btn-barra-play">
              <a href="#" class="btn btn-dark " onclick="playlist.nextTrack();">
                <i class="fa fa-fast-forward"></i>
              </a>
            </div>
          </div>
          <div class="col ">
            <div id="div-audio" class="ml-2">
              <div class="mb-4 " id="div-audio">
                <audio src="" controls id="audioPlayer">
                   Sorry, your browser doesn't support html5!
                 </audio>
              </div>
           </div>
          </div>
       </div>
     </div> 
    </div>