<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/fontawesome-all.min.css"> 
    <link rel="stylesheet" href="css/bootadmin.min.css">
    <link rel="stylesheet" href="css/dashboard.css">
    <title>Dashboard</title>
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand navbar-dark bg-laranja">
        <a class="sidebar-toggle mr-3" href="#"><i class="fa fa-bars"></i></a>
        <a class="navbar-brand" href="#">PlaySound</a>
        <div class="navbar-collapse collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a href="#" id="dd_user" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
                        <?php echo $_SESSION['nome'];?>
                        
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dd_user">
                        <a href="#" class="dropdown-item">Perfil</a>
                        <a href="/sair" class="dropdown-item">Sair</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="d-flex">
        <div class="sidebar sidebar-dark bg-dark bg-primary">
            <ul class="list-unstyled">
                <li id="btn-dashboard">
                    <a href="/dashboard"><i class="fa fa-fw fa-tachometer-alt"></i> Dashboard</a>
                </li>
                <li id="btn-upload">
                    <a href="/upload"><i class="fa fa-fw fa-cloud-upload-alt"></i> Upload</a></li>
                <li id="btn-musicas">
                    <a href="/minhas-musicas"><i class="fa fa-fw fa-headphones"></i> Músicas</a>
                </li>
                <li id="btn-cadastro">
                    <a href="/cadastro"><i class="fa fa-user-circle"></i> Cadastro</a>
                </li>
                <li id="btn-admins">
                    <a href="/admins"><i class="fa fa-users"></i> Admins</a>
                </li>
            </ul>
        </div> 
        <?=$this->content()?>
<script src="js/action.js"></script>
</html>    
</body>