<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/fontawesome-all.min.css">
    <link rel="stylesheet" type="text/css" href="css/index.css">
    <title>Sistema Playlist</title>
  </head>
  <body>
<?php
  include "include/header.phtml";
  echo $this->content();
  include "include/footer.phtml"; 
?>

   

   

